### ISSUE TITLE
CBLOCK

### ISSUE THREAD

**Issue by arRk-byte** [DeltaNedas/routorio#41]
**Platform**:
NVIDIA GPU/Windows 10

**Mindustry Version**:
135 alpha

**Routorio Version**: *the number please*
latest

**Describe the issue**:
cannot cblock property from null

**Steps to reproduce, including save file if non trivial**
Break any block

**Comment by arRk-byte** [comment]
latest as of the mod browser

**Comment by DeltaNedas** [comment]
cant reproduce and no log provided
